### ISSUE TITLE
The argument type 'double?' can't be assigned to the parameter type 'double' because 'double?' is nullable and 'double' isn't. iconSize: effectiveIconTheme.size,

### ISSUE THREAD

**Issue by Sunsiha** [tneotia/html-editor-enhanced#225] opened 2022-02-24 14:55 UTC
When I try to run the application getting this error.
```
../tools/flutter/.pub-cache/hosted/pub.dartlang.org/flex_color_picker-2.3.0/lib/src/widgets/color_picker_toolbar.dart:113:44: Error: The argument type 'double?' can't be assigned to the parameter type 'double' because 'double?' is nullable and 'double' isn't.
              iconSize: effectiveIconTheme.size,
```
Directly am not using this plugin. But this plugin is using color_picker_toolbar. So not able to figure it out how to fix it.

**Comment by rydmike** [comment] 2022-02-24 19:21
@tneotia for your info too, I started looking at this issue here https://github.com/rydmike/flex_color_picker/issues/40 but I have been unable to replicate the issue so far.

---

>OT:
Since you are not using the built in dialog for the picker, but have made your own version, which is perfectly fine, then this:

https://github.com/tneotia/html-editor-enhanced/blob/31406a4c0d6df0e9e8833057828dd8bf116df355/lib/src/widgets/toolbar_widget.dart#L1138
> Is not really needed. Since it does not do anything, not with the props you have set in it now.
>
>The button features starting with `dialog` in the config class naturally only have any impact when you use the pickers own built-in dialog and for the actions in it. With your own dialog and actions wrapping the color picker it has no impact. The toolbar config buttons (copy, paste, ok, close) in the same config class are in the picker itself, so they would show up, if you need them. 
>
> It was a bit lazy of me to not have them in separate config classes separating the concerns of the dialog configurable buttons and the ones for the toolbar in the picker. That would have been clearer. I'm going to at least add a note in API docs about this, too make it clearer.

**Comment by tneotia** [comment] 2022-02-24 23:20
Yeah this one is interesting, it seems to me its likely a Flutter related bug, not directly through this package (or flex color picker, for that matter).

**Comment by rydmike** [comment] 2022-02-24 23:30
@tneotia can you replicate the issue? I cannot, I tried. 

I would need a repro sample to get any further.

If you can reproduce it, please let me know and provide sample if you can. Otherwise if you can't replicate it either, it seems like a Flutter setup issue in @Sunsiha environment might also be the cause,. Which I mentioned as a possibility here https://github.com/rydmike/flex_color_picker/issues/40 too.

**Comment by LeDinhTrong** [comment] 2022-03-01 06:53
> @tneotia can you replicate the issue? I cannot, I tried.
> 
> I would need a repro sample to get any further.
> 
> If you can reproduce it, please let me know and provide sample if you can. Otherwise if you can't replicate it either, it seems like a Flutter setup issue in @Sunsiha environment might also be the cause,. Which I mentioned as a possibility here [rydmike/flex_color_picker#40](https://github.com/rydmike/flex_color_picker/issues/40) too.

/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flex_color_picker-2.3.0/lib/src/widgets/color_picker_toolbar.dart:113:44: Error: The argument type 'double?' can't be assigned to the parameter type 'double' because 'double?' is nullable and 'double' isn't.
              iconSize: effectiveIconTheme.size,
                                           ^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flex_color_picker-2.3.0/lib/src/widgets/color_picker_toolbar.dart:125:44: Error: The argument type 'double?' can't be assigned to the parameter type 'double' because 'double?' is nullable and 'double' isn't.
              iconSize: effectiveIconTheme.size,
                                           ^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flex_color_picker-2.3.0/lib/src/widgets/color_picker_toolbar.dart:137:44: Error: The argument type 'double?' can't be assigned to the parameter type 'double' because 'double?' is nullable and 'double' isn't.

              iconSize: effectiveIconTheme.size,
                                           ^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flex_color_picker-2.3.0/lib/src/widgets/color_picker_toolbar.dart:149:44: Error: The argument type 'double?' can't be assigned to the parameter type 'double' because 'double?' is nullable and 'double' isn't.
              iconSize: effectiveIconTheme.size,
                                           ^

* Where:
Script 'D:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1005

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, 2.5.3, on Microsoft Windows [Version 10.0.19044.1566], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.64.2)
[√] Connected device (3 available)

• No issues found!

**Comment by rydmike** [comment] 2022-03-03 13:25
For some reason in Flutter SDK version 2.8.1, `IconButton.iconSize` is not nullable, but in version 2.10.1 it is. 

It is a bit unusual that it has changed. **FlexColorPicker** has used it as nullable intentionally in many versions back. This none nullable issue should have bombed ages ago, if it was not nullable at some point before too. Maybe it was made none nullable for a few versions and then back to nullable again in 2.10. Or perhaps its usage like this, was indeed a remnant from much older nullable Flutter version of FlexColorPicker.

In any case the issue has been fixed in a way that is compatible with both Flutter SDK versions so it works regardless of if `IconButton.iconSize` is nullable or not. More info about the issue [#40 here](https://github.com/rydmike/flex_color_picker/issues/40) and [in PR #41](https://github.com/rydmike/flex_color_picker/pull/41).

Version 2.3.1 with the fix is published and [available on pub.dev now](https://pub.dev/packages/flex_color_picker/changelog).

It should auto updated into this package too when you use and do a `flutter pub upgrade` so its transitive deps are updated as high as they can. This `html-editor-enhanced` package has ^2.1.0 as version constraint on `flex_color_picker` so it should move up to ^2.3.1 without any issues, unless you have it in use via some other dependency with conflicting version limitation.

The parallel issue report [#40](https://github.com/rydmike/flex_color_picker/issues/40) in `flex_color_pikcer` repo has been closed. I think this issue can be closed now too.

Thanks you all for issue reports 💙  it helped with finding the rationale for the issue.

**Closed** 2022-04-07 00:02 UTC
Labels: bug
