### ISSUE TITLE
On Htmlwidget container close, sometimes getting attached issue.

### ISSUE THREAD

**Issue by akmichael** [tneotia/html-editor-enhanced#65] opened 2021-06-16 07:40 UTC
![html error](https://user-images.githubusercontent.com/8349884/122178362-22e01000-cea4-11eb-8e54-3d99a92601b6.PNG)

this issue occurs sometimes but frequently. how to fix this?

**Comment by tneotia** [comment] 2021-06-16 09:53
@akmichael what version of the plugin are you using? I tried to fix this on 2.2.0.

If you are using 2.2.0 and the error happens, could you send the code for your whole page so I can try and reproduce? Thanks.

**Comment by tneotia** [comment] 2021-06-17 12:33
Make sure you do not use 2.2.0+1-dev.1, use just 2.2.0 and try it. Flutter clean before you build.

2.2.0+1-dev.1 is only compatible with Flutter beta/dev/master for right now.

**Comment by akmichael** [comment] 2021-06-17 12:38
i reverted to back to old version html editor enhanced v.^2.1.1. and tried flutter clean, Invalidate caches/restart. still didnt help.

**Comment by tneotia** [comment] 2021-06-17 12:57
Set pubspec to 
```yaml
dependencies:
   html_editor_enhanced: ^2.2.0

dependency_overrides:
   flutter_colorpicker: ^0.4.0
```

**Comment by tneotia** [comment] 2021-06-17 13:23
> Thanks. nice, it works now. even i dont see flickering issue on parent widget close now, which I reported earlier. (y) 

That's great. I will confirm the flickering issue is gone and then will close that issue.

> there is one issue i noticed. when i press return key (new line) at the last word, new line not not shown immedicately. cursor is still in same line. but exists in gettext() method. when I assign gettext() value to html control, new empty lines exist.

I notice this all the time as well but nobody else had reported it so I thought it was an issue with my device/configuration. Please open a separate issue and I will look into it, I remember trying to figure this out earlier but I couldn't find any solution.

**Comment by akmichael** [comment] 2021-06-17 18:43
attached my code to reproduce above screenshot error.

steps:

- edit some text in htmleditor
- click save (right corner)
- click close (left corner).

`import 'package:flutter/material.dart';
import 'package:html_editor_enhanced/html_editor.dart';

class UpdateViewPage extends StatefulWidget {

  UpdateViewPage();

  @override
  _UpdateViewPageState createState() =>
      _UpdateViewPageState();
}

class _UpdateViewPageState extends State<UpdateViewPage> {

  _UpdateViewPageState();

  HtmlEditorController htmlController = HtmlEditorController();
  bool isSaveInProgress = false;

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Update"),
        leading: new IconButton(
          icon: new Icon(Icons.close),
          onPressed: () => Navigator.of(context).pop(null),
        ),
        actions: !isSaveInProgress
            ? <Widget>[
          new IconButton(
              icon: new Icon(Icons.save),
              onPressed: () async{

                await Future.delayed(Duration(seconds: 2));

              })
        ]
            : <Widget>[
          Padding(
            padding: EdgeInsets.only(right: 20),
            child: Center(
              heightFactor: 1,
              widthFactor: 1,
              child: SizedBox(
                height: 24,
                width: 24,
                child: CircularProgressIndicator(
                ),
              ),
            ),
          )
        ],
        backgroundColor: Color.fromRGBO(55, 64, 71, 1.0),
      ),
      body: Container(
        margin: const EdgeInsets.only(top: 15, left: 15, right: 15),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          mainAxisSize: MainAxisSize.max,
          children: <Widget>[
            Padding(
                padding: EdgeInsets.all(4.0),
                child: HtmlEditor(
                    controller: htmlController, //required
                    htmlEditorOptions: HtmlEditorOptions(
                      initialText: "demotext",
                    ),
                    otherOptions: OtherOptions(
                      height: 180,
                    ),
                    htmlToolbarOptions:
                    HtmlToolbarOptions(defaultToolbarButtons: [
                      ParagraphButtons(lineHeight: false, caseConverter: false)
                    ]))),
          ],
        ),
      ),
    );
  }
}`

**Comment by tneotia** [comment] 2021-06-17 21:25
Thanks, I tried it but cannot reproduce with the latest release so I think this is solved. Is it still happening for you?

**Comment by akmichael** [comment] 2021-06-18 05:59
yes. it is keeps occurring everytime. I am testing in android.

**Comment by tneotia** [comment] 2021-06-18 09:48
Hmmm, I'm also testing on Android. I looked at the screenshot again and I now see you show the line the issue is at. I will take a look into this today and I think I may know how to fix it.

**Comment by tneotia** [comment] 2021-06-18 23:16
I have pushed a fix, could you try `master` branch and see if it occurs now?

**Comment by tneotia** [comment] 2021-06-29 22:27
Closing for now, please let me know if this is still an issue. Thanks!

**Closed by tneotia** 2021-06-29 22:27 UTC
Labels: bug
