### ISSUE TITLE
Add File type in onImageUpload Callback

### ISSUE THREAD

**Issue by indjec** [tneotia/html-editor-enhanced#19] opened 2021-03-31 05:28 UTC
My server accepts an argument of File so i can't upload images as bytes from my editor

**Comment by tneotia** [comment] 2021-03-31 14:16
Is there any error you are encountering using bytes? An error report (or possibly even a test URL to your server) would be helpful, that way I can try and figure out why that is.

I tested using a [pipedream](https://pipedream.com/) test server and files uploaded via bytes work perfectly. Here's my test code using Dart http package:
```dart
import 'dart:convert';
import 'dart:typed_data';
import 'package:http/http.dart' as http;
```
and 
```dart
onImageUpload: (FileUpload file) async {
   Uint8List bytes = base64.decode(file.base64!.split(",")[1]);
   var request = http.MultipartRequest('POST', Uri.parse("my_pipedream_test_server_url"));
   request.files.add(http.MultipartFile.fromBytes("file", bytes, filename: file.name));
   var response = await request.send();
   print(response.statusCode);
},
```
I get 200 status and when I download the file on my laptop it looks normal.

The reason I feel that it should work on your end is because any web-based upload is going to use bytes to upload, as I mentioned previously the file path is not exposed to any webviews. At its core, I'm fairly certain that is what `File` does as well. It opens the file as bytes and uploads it to the server, which then pieces it back into a file. Please respond though because I'd like to help you resolve this issue.

**Comment by indjec** [comment] 2021-04-01 11:24
Thanks its working for me..But idk why my image gets automatically rotated when i upload from my app, but it works fine from postman.

**Comment by tneotia** [comment] 2021-04-01 11:28
Great!

Rotation is odd, base64 shouldn't affect that, maybe your server is doing it? I don't know much about how files are handled once received by the server so I can't help much with that.

Since the issue is solved is it ok to close this?

**Comment by indjec** [comment] 2021-04-01 11:28
Sure.

**Closed** 2021-04-01 11:29 UTC
Labels: enhancement
