### ISSUE TITLE
[BUG] Dark mode white background color of Text

### ISSUE THREAD

**Issue by Huanxin1997** [tneotia/html-editor-enhanced#175] opened 2021-11-24 10:09 UTC
**Describe the bug**
In dark mode, when click such button , white background color is inserted.
![image](https://user-images.githubusercontent.com/42678103/143218177-d899fa3c-9ca9-4e38-bfce-86127da2f1ad.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/42678103/143217923-308c95d8-aa9f-466b-8002-bed6481c348a.png)

**Comment by tneotia** [comment] 2021-11-24 12:48
Closing as duplicate of other issue.

**Closed** 2021-11-24 12:48 UTC
Labels: bug
