### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nimr77** [tneotia/html-editor-enhanced#287] opened 2022-07-13 14:22 UTC
**Describe the bug**
once I put a dialog or any widget on top of the widget that has the HTML editor, the cursor stays as focused on the editor

**To Reproduce**
1. create a widget with an HTML editor
2. open a dialog above it
3. just put the mouse on the dialog and make sure that the dialog is on top of the HTML editor
4. See the cursor

FLUTTER WEB

**### Screenshot**

![Screenshot from 2022-07-13 15-15-55](https://user-images.githubusercontent.com/36929077/178756754-351fa01e-46c7-4b85-95fe-7d414a162e05.png)

**Comment by tneotia** [comment] 2022-07-15 18:28
Duplicate of #270

**Closed by tneotia** 2022-07-15 18:28 UTC
Labels: bug
