### ISSUE TITLE
Terminal error messages

### ISSUE THREAD

**Issue by blue492** [tneotia/html-editor-enhanced#34] opened 2021-05-03 11:18 UTC
I upgraded to html_editor_enhanced 2.0.1 today, it works well, thanks for your work. I have html-editor-enhanced in separate page and when I do the following
```
    final result = await controller.getText(); 

    if( Navigator.canPop(context) == true) {
      Navigator.pop(context, result);
    }
```
It show the following error messages in Terminal:
```
W/ImageReader_JNI(14972): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
E/flutter (14972): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Bad state: No element
E/flutter (14972): #0      Stream.first.<anonymous closure> (dart:async/stream.dart:1213:9)
E/flutter (14972): #1      _rootRun (dart:async/zone.dart:1346:47)
E/flutter (14972): #2      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (14972): #3      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (14972): #4      _DoneStreamSubscription._sendDone (dart:async/stream_impl.dart:785:36)
E/flutter (14972): #5      _rootRun (dart:async/zone.dart:1354:13)
E/flutter (14972): #6      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (14972): #7      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (14972): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (14972): #9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (14972): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (14972): 
E/flutter (14972): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Bad state: No element
E/flutter (14972): #0      Stream.first.<anonymous closure> (dart:async/stream.dart:1213:9)
E/flutter (14972): #1      _rootRun (dart:async/zone.dart:1346:47)
E/flutter (14972): #2      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (14972): #3      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (14972): #4      _DoneStreamSubscription._sendDone (dart:async/stream_impl.dart:785:36)
E/flutter (14972): #5      _rootRun (dart:async/zone.dart:1354:13)
E/flutter (14972): #6      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (14972): #7      _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
E/flutter (14972): #8      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
E/flutter (14972): #9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (14972): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (14972): 
I/flutter (14972): setState() called after dispose(): ToolbarWidgetState#c9475(lifecycle state: defunct, not mounted)
I/flutter (14972): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
I/flutter (14972): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
I/flutter (14972): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/chromium(14972): [ERROR:aw_browser_terminator.cc(125)] Renderer process (15434) crash detected (code -1).
W/ImageReader_JNI(14972): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers

```

**Comment by rajatKumar023** [comment] 2021-05-03 14:06
I am also getting the same error messages

**Comment by tneotia** [comment] 2021-05-04 03:37
I was able to fix the 

```
I/flutter (14972): setState() called after dispose(): ToolbarWidgetState#c9475(lifecycle state: defunct, not mounted)
I/flutter (14972): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
I/flutter (14972): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
I/flutter (14972): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/chromium(14972): [ERROR:aw_browser_terminator.cc(125)] Renderer process (15434) crash detected (code -1).
W/ImageReader_JNI(14972): Unable to acquire a buffer item, very likely client tried to acquire more than maxImages buffers
```

error but I have no idea for the `Bad State: No element` error. There is no line number for any code in the package but I can reproduce in the example app, maybe it's an issue with a dependency? I only use a `Stream` in one place (for height detection) and there are no issues with the `.first` I use with the stream - I check `mounted` before calling `.first`.

I will keep monitoring this, the error does not hurt the functionality or cause a crash which is good.

**Comment by tneotia** [comment] 2021-05-05 16:19
Somehow I got the other errors to fix... There must have been some change to `<stream controller>.drain()` because it was messing with the height adjustment and causing this error. Closing this, it will be pushed out in a new release once I complete #32 (you can use git dependency if you need it immediately). 

Thanks for the report!

**Closed by tneotia** 2021-05-05 16:19 UTC
Labels: help wanted

**Comment by MRezaKarimi** [comment] 2022-01-23 11:15
I have the same issue.
Error occurs only when some text is typed in editor (or editor is in focus) and I tap back bottom and navigate to previous page.

**Comment by tneotia** [comment] 2022-01-25 22:25
> I have the same issue. Error occurs only when some text is typed in editor (or editor is in focus) and I tap back bottom and navigate to previous page.

Can you provide stacktrace please :)

**Comment by MRezaKarimi** [comment] 2022-01-26 13:31
> > I have the same issue. Error occurs only when some text is typed in editor (or editor is in focus) and I tap back bottom and navigate to previous page.
> 
> Can you provide stacktrace please :)

![Screenshot from 2022-01-26 17-00-31](https://user-images.githubusercontent.com/39339552/151171842-356f874d-bce2-4b33-9dcc-822b0b4c5d3b.png)

**Comment by tneotia** [comment] 2022-01-29 19:04
Hmm seems unrelated to the editor/package (at least I think because there is no line number for the package itself, it is all dart internal line numbers).
