### ISSUE TITLE
[BUG] When i use controller.insertHtml(); method in web it doesn't work and throws this message. What can be reason

### ISSUE THREAD

**Issue by mamasd** [tneotia/html-editor-enhanced#23] opened 2021-04-10 08:52 UTC
Type question here.
```
TypeError: Cannot read property 'includes' of null
                at handleMessage (about:srcdoc:47:30)
```

**Comment by tneotia** [comment] 2021-04-10 11:05
Hmm this is a bug in the javascript code, I'll look into this. Could you post your widget code to make sure I can replicate it?

**Comment by tneotia** [comment] 2021-04-10 18:39
I tried this using the example app but I could not reproduce (click the Insert HTML button below the editor).

**Comment by tneotia** [comment] 2021-04-14 13:23
Without further details I will close this, let me know if it is still an issue. Thanks.

**Closed by tneotia** 2021-04-14 13:23 UTC
Labels: awaiting-response, bug

**Comment by Achudh** [comment] 2022-06-11 13:00
> I tried this using the example app but I could not reproduce it (click the Insert HTML button below the editor).

I got this error when I'm loading the text in the init state
@tneotia  the issue still exists.
